name: Build and deploy Node.js app to Azure Web App - okta-test-gabe

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --prod
      working-directory: .
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'okta-test-gabe'
        publish-profile: '<publishData><publishProfile profileName="okta-test-gabe - Web Deploy" publishMethod="MSDeploy" publishUrl="okta-test-gabe.scm.azurewebsites.net:443" msdeploySite="okta-test-gabe" userName="$okta-test-gabe" userPWD="4ttERnB1zxm7C7Swf2Zhk5QWN3doePX0RwA0aCr00JRx9brdNqWz9MsSE3hS" destinationAppUrl="http://okta-test-gabe.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="okta-test-gabe - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-dm1-207.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="okta-test-gabe\$okta-test-gabe" userPWD="4ttERnB1zxm7C7Swf2Zhk5QWN3doePX0RwA0aCr00JRx9brdNqWz9MsSE3hS" destinationAppUrl="http://okta-test-gabe.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="okta-test-gabe - Zip Deploy" publishMethod="ZipDeploy" publishUrl="okta-test-gabe.scm.azurewebsites.net:443" userName="$okta-test-gabe" userPWD="4ttERnB1zxm7C7Swf2Zhk5QWN3doePX0RwA0aCr00JRx9brdNqWz9MsSE3hS" destinationAppUrl="http://okta-test-gabe.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'
        package: ./dist/okta-hosted-login
